### ISSUE TITLE
request for RFC: keyspace partitioning pattern

### ISSUE THREAD

**Issue by gregwebs** [tikv/rfcs#15]
When multiple applications store data in TiKV, there should be a clear pattern for avoiding conflicting use of the keyspace.

I have seen a directory concept in FoundationDB: a logical hierarchy with non-hierarchical physical representation.

FoundationDB links
* [Namespace](https://apple.github.io/foundationdb/developer-guide.html#developer-guide-namespace-management)
* [Subspace](https://apple.github.io/foundationdb/developer-guide.html#developer-guide-subspaces)
* [Directory](https://apple.github.io/foundationdb/developer-guide.html#developer-guide-directories)

FoundationDB does not use RocksDB. Column families from RocksDB may make our solutions easy to implement. However, we may want to support other storage engines that don't have column families: we may also need to consider how we would implement a column family abstraction for them.

**Comment by karthicks** [comment]
I second this RFC, as partitioning the `TiKV` database (into say tables) buys us the ability to:

- Avoid collisions in keys across multiple tables, reducing user error,
- Shard table-specific data more evenly, thus improving performance,
- Configure different tables independently (as noted in [the RocksDB wiki](https://github.com/facebook/rocksdb/wiki/Column-Families)),
- Replicate different table independently (corollary to the previous point),
- Reduce the complexity of the scan queries, by scoping it to the table.

One could surface this feature on the client as a `tableName` property in the `config` object used to create a `TiKV` client, which if not specified defaults to some `default` table name. 

Here are some pointers to reference implementations that provide this kind of feature:
- [RocksDB Column Family](https://github.com/facebook/rocksdb/wiki/Column-Families)
- [HBase Table](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/client/Table.html)
- [Ignite Cache](https://ignite.apache.org/releases/latest/javadoc/index.html)
- [Riak Bucket](https://docs.riak.com/riak/kv/latest/learn/concepts/buckets/index.html)
- [ArangoDB Collection](https://www.arangodb.com/docs/stable/drivers/java-reference-database-collection-access.html)

**Comment by gregwebs** [comment]
I believe the most pressing concern is to allow different applications to ensure their keys will not conflict. But helping applications organize their data into tables could use the same mechanisms. TiDB has managed to organize data into tables already without help from TiKV.

**Comment by gregwebs** [comment]
I looked into foundationDB's directories a bit more. I don't understand the benefit of the directory structure, but the thing that it does do which is definitely useful is that it abstracts over the key prefix such that it gives a shortened prefix and the prefix can be changed (e.g. backup + restore). They generally recommend that each application creates its own directory entry but then manage subspaces itself from there. AFAICT directories are implemented as a layer, which creates an issue because it requires network latency to check that the directory prefix has not changed. Additionally, fdb has no authentication, but were it added, it would not be well integrated with directories.

For TiKV I always imagined that the basis of keyspaces would look like fdb's directories in that it abstracts over key prefix, although I am unsure about the utility of directory hierarchy. But crucially this should be implemented directly in TiKV.

**Comment by siddontang** [comment]
@gregwebs 

Maybe you can share your doc here, IMO, I think using key prefix is a good way, e.g. each TiDB server has a prefix which represents an account, and every request sent to TiKV contains the prefix, so TiKV can support multi-tenant directly.

**Comment by gregwebs** [comment]
Yes, I can help develop the RFC. Yes, the concept I have is just for different applications to use different key prefixes. I believe it is best to formalize this with a key space concept. The design I have in mind is as per above somewhat similar to FDB's directory feature.

**Comment by gregwebs** [comment]
I created an RFC: #39
