### ISSUE TITLE
Should we give each RFC an numeric identifier?

### ISSUE THREAD

**Issue by MyonKeminta** [tikv/rfcs#22]
I see in other projects' RFCs, they usually mark RFCs with a simple number. Then when they references to a certain RFC, they simply says "RFC #1234". And the number usually is the pull request ID that proposes that RFC. Should we also do like this?

**Comment by BusyJay** [comment]
A good idea! Can you make a pull request to make it a rule?

**Comment by MyonKeminta** [comment]
Sure

**Comment by MyonKeminta** [comment]
But I have another question. It seems that in projects like `rust-lang/rfcs`, people don't number their new RFCs immediately. However, after merging it to master, there will be a manager to the repo add another commit to number the new added RFC. It seems that this workflow is common in many RFC repos. I'm not sure why they do that. This workflow seems not to be very suitable for us since we don't allow pushing to master or merging PR without approving reviews.
