### ISSUE TITLE
Include titles in RFC

### ISSUE THREAD

**Issue by breeswish** [tikv/rfcs#9]
Currently our RFC don't have titles. I suggest to change the template to include a title for the RFC:

```markdown
# Title

## Summary

...

## Motivation

...
```

**Comment by siddontang** [comment]
The format is referred from Rust and crossbeam, and the file name has already shown the title, I think it is ok.

If you really want to add a title, you can include some fields like https://github.com/rust-lang/rfcs/blob/master/0000-template.md

**Comment by breeswish** [comment]
Oh. So it seems that these RFCs don't have titles, but only unique identifiers (names) to be easily referred. I think this is a good idea. Closing.
